### ISSUE TITLE
"Must install .NET"

### ISSUE THREAD

**Issue by dcorvus** [iXyles/UtilityBox#1]
I keep receiving the error:
![](https://i.imgur.com/pobhaKk.png)

Despite having installed version 5.0.4 and reinstalled it multiple times as well as restarting the PC. Regardless of what I do it won't run. Using the latest Alpha Version v0.1.1.0

**Comment by iXyles** [comment]
V5.0.4? That is not a version of .NET 5 - Latest is 5.0.2 : https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.102-windows-x64-installer

**Comment by dcorvus** [comment]
> V5.0.4? That is not a version of .NET 5 - Latest is 5.0.2 : https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.102-windows-x64-installer 

Oof. Yeah, sorry. Was looking at something else while typing and got sidetracked, but yes it's the latest one. Installed it straight from the link in the popup.

**Comment by iXyles** [comment]
Can you try install this and see if it works
https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.2-windows-x64-installer

**Comment by dcorvus** [comment]
Yeah, that worked. It's odd though that the direct link in the windows alert sent me to https://dotnet.microsoft.com/download/dotnet/5.0/runtime/?utm_source=getdotnetcore&utm_medium=referral instead of the aspnetcore. I didn't even notice it until this morning.

Now I'm stuck in a perpetual "System is not ready... Please wait."

**Comment by iXyles** [comment]
That is when something goes wrong internally during the startup process most of the time.
I'll have to try in a logger of somekind of why it happen to try to debug it.

What version of Windows are you running btw? 
Might do an update regarding this during the week.

**Comment by dcorvus** [comment]
Sorry for the late reply. I'm running Windows 10 Enterprise, Version 20H2.

**Comment by iXyles** [comment]
Sorry for the delay, are you able to try this and let me know what type of "exception" window shows up?

https://github.com/iXyles/UtilityBox/releases/tag/v0.1.2.0

**Comment by iXyles** [comment]
Temporary solution around the issue do this:

Open CMD as admin and type this
`dotnet dev-certs https --clean`
`dotnet dev-certs https -t`

I will make sure this is automatically done or done in a different way in the future versions.

**Comment by iXyles** [comment]
https://github.com/iXyles/UtilityBox/releases/tag/v0.2.0.0

The work around described above shall no longer be required.

**Comment by ByteSizedMarius** [comment]
Clicking "download it now - yes" redirects me to .net runtime https://dotnet.microsoft.com/download/dotnet/5.0/runtime/?utm_source=getdotnetcore&utm_medium=referral.  This wont work.

Downloading the .net sdk will. I think the hardcoded link might be wrong. Win10 enterprise aswell, but don't think that matters.

**Comment by iXyles** [comment]
Hello Marius, 

The URL displayed in the popup by the program is not set by me... It is automatically set by the framework of Microsoft and sadly out of my hands to change.
Thats why I wrote in the github page that you must download the SDK part and not only the runtime.
The reason I did this way is because otherwise the app would be 200-500Mb

Br
