### ISSUE TITLE
System is not ready...Please wait.

### ISSUE THREAD

**Issue by mul00t** [iXyles/UtilityBox#2]
After starting the App, it minimizes in the Systemtray and stays there.
When i click on it, it opens a window saying: "System is not ready...Please wait."
No change after 30min.

![System is not ready Please wait](https://user-images.githubusercontent.com/78370335/106484967-6b2c0200-64b0-11eb-8cc7-9d9c9399f4d8.PNG)

Programm was installed with admin rights.

NET Core 5.0.2 installed
Windows 10 Pro
Version: 10.0.19042

**Comment by iXyles** [comment]
Most likely similar issue to the previous registered one.

I'll try to add in some sort of logging support during the weekend and deploy a new version to try figure out the cause of this.

Thanks for reporting

**Comment by mul00t** [comment]
No problem, thank you for this great piece of software you're working on, really appreciate it.

**Comment by Sethypie** [comment]
Same issue for me

**Comment by iXyles** [comment]
Sorry for the delay, are you able to try this and let me know what type of "exception" window shows up?

https://github.com/iXyles/UtilityBox/releases/tag/v0.1.2.0

**Comment by Sethypie** [comment]
Uninstalled and installed the newest version.
I am receiving an "Unable to configure HHTPS endpoint. No server certificate was specified."

**Comment by iXyles** [comment]
Thank you!

Could you try to start CMD as admin and type this
`dotnet dev-certs https --clean`
`dotnet dev-certs https -t`

Then try restart the tool

**Comment by Sethypie** [comment]
Yep all seems to work fine now, thanks!

**Comment by iXyles** [comment]
Alright, then I know what is causing the issue and to resolve it.
I'll have to re-think how I do some things then, thanks for letting me know :)
