### ISSUE TITLE
Microsoft Defender SmartScreen Warning

### ISSUE THREAD

**Issue by Eddga** [iXyles/UtilityBox#3]
When running the latest UtilityBox.App.0.2.0.0.exe installer Microsoft Defender SmartScreen pops up and warns me off the app being unrecognized.
It's not a deal breaker as one can still continue with the installation by clicking "More info" and "Run anyway". Therefore it's a really low priority issue.
I don't know if it's worth your time signing/validating the app as the process seems to take a bit of time according to this thread: https://stackoverflow.com/questions/12311203/how-to-pass-the-smart-screen-on-win8-when-install-a-signed-application
But I just wanted to let you know. 

I'm running Windows 10 Pro 20H2 (19042.867).

The window says:

> Windows protected your PC
Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.
App: UtilityBox.App.0.2.0.0.exe
Publisher: Unknown publisher
More info ->
Run anyway  / Don't run

Kind regards
Eddga

**Comment by iXyles** [comment]
Hello,

Yes I am aware of this. And consider it is a free tool, and I do not own a code signing cert I cannot resolve this, unless someone would freely pay for the cert which would be somewhere between $500-700/year. Which I am not interested of paying from my own pocket for a tool which is available to download & compile your own if there would be any concerns.

The original tool was downloaded roughly 140,000 before I decided to do this new version of it.

Br

**Comment by Eddga** [comment]
Ah ok. In the linked thread on stackoverflow it sounded like there were simple free ways of signing the app. In that case I wouldn't spend any money on that either. 👍
