### ISSUE TITLE
Exit in Web UI not working

### ISSUE THREAD

**Issue by Eddga** [iXyles/UtilityBox#4]
Trying to exit the UtilityBox via browser UI does nothing.
Clicking on Exit in the browser UI neither closes the browser tab, nor does it exit the desktop app, that runs in tray/background.
Besides that at first glance everything seems to be working.

I'm running Windows 10 Pro 20H2 (19042.867) have the browser UI opened in Google Chrome x64 version 89.0.4389.90

Kind regards
Eddga

**Comment by iXyles** [comment]
Hello,

That is correct, the background service is a webserver that is runned on your local machine. This way the tool is available through a browser with a nicer interface than a usual "windows form" which looks quite boring if you were to ask me.
It also simplifies the process of adding new functionality in an easier manner if someone wish to edit the code base of their own.

To close the service, you'll just as any regular "tray" program, right click it and close it.

Br

**Comment by Eddga** [comment]
But why is the "Exit" option even there in the browser UI if it is intended to do nothing?
Or am I misunderstanding something?

**Comment by iXyles** [comment]
Oh I see what you mean now haha, that is not even meant to be there, I think I was using it during debugging.

NOTE: I will fix this for the next version.

**Comment by iXyles** [comment]
Will be fixed part of V.0.3.0
