### ISSUE TITLE
UtilityBox is not opening even if the .NET 5.0 is installed. 

### ISSUE THREAD

**Issue by Risto15** [iXyles/UtilityBox#5]
Basically as soon as I tried to open the program, a message popped up saying that framework 5.0 is not installed.
At first I was like: "Oh, okay, I am going to download the framework" but it didn't work.
I tried re-opening the program, still nothing.
Then I restarted my pc and the same message was still popping up, then I repaired framework and still nothing, so I thought it would best to ask you for help.
Thanks for any advices!

**Comment by iXyles** [comment]
Please try install this: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.2-windows-x64-installer

And let me know if the issues contiues.
Br
